name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Lint
        id: yarn-lint
        run: yarn lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          out-file: 'test.txt'

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.return }}"
