name: Deploy

on:
  workflow_run:
    workflows: ['Continuous Integration']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Add new release
        run: |
          gh release create v${{ steps.package-version.outputs.current-version}}
